name: xpath_selector_example
description: A xml parser implementation with xml for xpath_selector
version: 1.0.0


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  xpath_selector:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
