name: xpath_selector_example
description: A xml parser implementation with xml for xpath_selector
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  xpath_selector: ^3.0.0
  xpath_selector_html_parser: ^3.0.0
  xpath_selector_xml_parser: ^3.0.0


dev_dependencies:
  lints: ^2.0.0

