name: xpath_selector_example
description: A xml parser implementation with xml for xpath_selector
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  xpath_selector:
    path: ../
#  xpath_selector_html_parser:
#    path: ../../xpath_selector_html_parser
#  xpath_selector_xml_parser:
#    path: ../../xpath_selector_xml_parser

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
