name: xpath_selector_xml_parser
description: A xml parser implementation with xml for xpath_selector
version: 3.0.0
homepage: https://github.com/simonkimi/xpath_selector



environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xpath_selector: any
  xml: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
